replicasCount: 1
fullName: "ms-smtp-server"
selectorLabel: "ms-smtp-server"


ports:
    smtpSecure: 8465
    smtpAuth: 8587

mailHost: "smtp.solenopsys.org"
container:
  name: router
  image: registry.solenopsys.org/solenopsys-mail
  pullPolicy: Always